FROM ubuntu:bionic

ENV OS_IDENTIFIER ubuntu-1804

RUN set -x \
  && sed -i "s|# deb-src|deb-src|g" /etc/apt/sources.list \
  && export DEBIAN_FRONTEND=noninteractive \
  && apt-get update \
  && apt-get install -y libcurl4-openssl-dev libicu-dev wget python-pip \
  && apt-get build-dep -y r-base

RUN pip install awscli

RUN chmod 0777 /opt

# Override the default pager used by R
ENV PAGER /usr/bin/pager

COPY build.sh .
ENTRYPOINT ./build.sh
