name: Check for new R versions

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
    inputs:
      publish:
        description: |
          Publish the builds to S3 staging or production? Defaults to staging.
        required: false
        default: 'staging'
        type: choice
        options:
          - staging
          - production

permissions:
  id-token: write
  contents: read

jobs:
  check-r-versions:
    runs-on: ubuntu-latest
    outputs:
      new_r_versions: ${{ steps.setup-check_r_versions.outputs.new_r_versions }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Check for new R versions to build
        id: check_r_versions
        run: |
          new_r_versions=$(python manage_r_versions.py check --s3-bucket="${{ secrets.S3_BUCKET_PRODUCTION }})"
          echo "$new_r_versions"
          echo "new_r_versions=$new_r_versions" >> $GITHUB_OUTPUT

  build-new-r-versions:
    needs: check-r-versions
    if: ${{ needs.check-r-versions.outputs.new_r_versions != '' }}
    uses: ./.github/workflows/build.yml
    with:
      r_versions: ${{ needs.check_r_versions.outputs.new_r_versions }}
      publish: ${{ inputs.publish || 'production' }}
    secrets: inherit
